export default [
	{
		id: 1,
		type: 'Full-Stack',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 2,
		type: 'UI/UX',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 3,
		type: 'API',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 4,
		type: '',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 5,
		type: 'Full-Stack',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 6,
		type: 'Full-Stack',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 7,
		type: 'Full-Stack',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
	{
		id: 8,
		type: 'Full-Stack',
		title: 'My app',
		link: 'https://linkedin.com',
		image: 'https://i.imgur.com/rMBkVQX.png',
	},
]
